version: "3.9"

services:
  database:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: quadro_societario
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: root
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data:rw
